import {createHash,createPublicKey,randomBytes,timingSafeEqual,verify as verifySignature} from "node:crypto";
import {mkdir,open,readFile,readdir,rename,writeFile} from "node:fs/promises";
import {join,resolve} from "node:path";

export const CREATOR_PASSKEY_FORMAT="arca-creator-passkey-v1";
export const CREATOR_PASSKEY_VERSION="0.1.0";
export const CREATOR_PASSKEY_ASSERTION_FORMAT="arca-creator-passkey-assertion-v1";

const HASH=/^[a-f0-9]{64}$/;
const B64URL=/^[A-Za-z0-9_-]{1,4096}$/;
const SAFE_LABEL=/^[^\u0000-\u001f\u007f]{1,160}$/;
const MAX_RECORD_BYTES=128*1024;
const DEFAULT_CHALLENGE_TTL_MS=2*60*1000;

type JsonObject=Record<string,any>;
type ChallengePurpose="register"|"authenticate"|"step-up";

type CborDecoded={value:any;offset:number};

function plain(value:unknown):value is JsonObject{return !!value&&typeof value==="object"&&!Array.isArray(value)}
function clean(value:any):any{if(Array.isArray(value))return value.map(clean);if(plain(value)){const out:JsonObject={};for(const [key,item] of Object.entries(value))if(item!==undefined)out[key]=clean(item);return out}return value}
function stable(value:any):string{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(plain(value))return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value)}
function sha256Bytes(value:Buffer|string){return createHash("sha256").update(value).digest()}
function sha256(value:any){return createHash("sha256").update(typeof value==="string"?value:stable(value)).digest("hex")}
function bodyForHash(record:JsonObject){const {recordHash:_ignored,...body}=record;return body}
function seal(record:JsonObject){const body=clean(record);return {...body,recordHash:sha256(body)}}
function b64url(bytes:Buffer|Uint8Array){return Buffer.from(bytes).toString("base64url")}
function bytes(value:unknown,label:string){if(typeof value!=="string"||!B64URL.test(value))throw new Error(`${label} invalido`);const out=Buffer.from(value,"base64url");if(!out.length)throw new Error(`${label} vazio`);return out}
function safeLabel(value:unknown){if(value===undefined||value===null||value==="")return null;if(typeof value!=="string"||!SAFE_LABEL.test(value.trim()))throw new Error("label de passkey invalido");return value.trim()}
function constantEqualHex(left:string,right:string){if(left.length!==right.length)return false;return timingSafeEqual(Buffer.from(left),Buffer.from(right))}
function uint(bytesValue:Buffer,offset:number,length:number){if(offset+length>bytesValue.length)throw new Error("CBOR truncado");if(length===1)return bytesValue.readUInt8(offset);if(length===2)return bytesValue.readUInt16BE(offset);if(length===4)return bytesValue.readUInt32BE(offset);if(length===8){const value=bytesValue.readBigUInt64BE(offset);if(value>BigInt(Number.MAX_SAFE_INTEGER))throw new Error("inteiro CBOR excede safe integer");return Number(value)}throw new Error("comprimento inteiro CBOR invalido")}
function cborLength(input:Buffer,offset:number,additional:number){if(additional<24)return {length:additional,offset};if(additional===24)return {length:uint(input,offset,1),offset:offset+1};if(additional===25)return {length:uint(input,offset,2),offset:offset+2};if(additional===26)return {length:uint(input,offset,4),offset:offset+4};if(additional===27)return {length:uint(input,offset,8),offset:offset+8};throw new Error("CBOR indefinido/unsupported recusado")}
function decodeCbor(input:Buffer,offset=0):CborDecoded{
  if(offset>=input.length)throw new Error("CBOR vazio/truncado");const initial=input[offset++];const major=initial>>5;const additional=initial&31;
  if(major===0||major===1){const info=cborLength(input,offset,additional);const value=major===0?info.length:-1-info.length;return {value,offset:info.offset}}
  if(major===2||major===3){const info=cborLength(input,offset,additional);const end=info.offset+info.length;if(end>input.length)throw new Error("CBOR bytes/text truncado");const slice=input.subarray(info.offset,end);return {value:major===2?Buffer.from(slice):slice.toString("utf8"),offset:end}}
  if(major===4){const info=cborLength(input,offset,additional);const values=[];let cursor=info.offset;for(let i=0;i<info.length;i++){const decoded=decodeCbor(input,cursor);values.push(decoded.value);cursor=decoded.offset}return {value:values,offset:cursor}}
  if(major===5){const info=cborLength(input,offset,additional);const map=new Map<any,any>();let cursor=info.offset;for(let i=0;i<info.length;i++){const key=decodeCbor(input,cursor);const value=decodeCbor(input,key.offset);map.set(key.value,value.value);cursor=value.offset}return {value:map,offset:cursor}}
  if(major===6){const info=cborLength(input,offset,additional);return decodeCbor(input,info.offset)}
  if(major===7){if(additional===20)return {value:false,offset};if(additional===21)return {value:true,offset};if(additional===22)return {value:null,offset};throw new Error("CBOR simple/float unsupported")}
  throw new Error("CBOR major type unsupported");
}
function mapValue(value:any,key:any){if(!(value instanceof Map))throw new Error("CBOR map esperado");return value.get(key)}
function normalizeOrigin(value:string){const url=new URL(value);if(!["https:","http:"].includes(url.protocol))throw new Error("origin deve usar HTTP(S)");const host=url.hostname.replace(/^\[|\]$/g,"").toLowerCase();if(url.protocol==="http:"&&!(["localhost","127.0.0.1","::1"].includes(host)))throw new Error("HTTP para passkey permitido somente em loopback");return url.origin}
function normalizeRpId(value:string){const rpId=String(value??"").trim().toLowerCase();if(!rpId||rpId.includes(":")||rpId.includes("/")||rpId.length>253)throw new Error("rpId invalido");return rpId}
function parseClientData(encoded:unknown){const raw=bytes(encoded,"clientDataJSON");let value:any;try{value=JSON.parse(raw.toString("utf8"))}catch{throw new Error("clientDataJSON invalido")};if(!plain(value))throw new Error("clientDataJSON deve ser objeto");return {raw,value}}
function verifyClientData(input:{encoded:unknown;expectedType:string;expectedChallenge:string;allowedOrigins:Set<string>}){const {raw,value}=parseClientData(input.encoded);if(value.type!==input.expectedType)throw new Error(`WebAuthn clientData type invalido: ${String(value.type)}`);if(typeof value.challenge!=="string"||value.challenge!==input.expectedChallenge)throw new Error("WebAuthn challenge divergente");if(typeof value.origin!=="string"||!input.allowedOrigins.has(normalizeOrigin(value.origin)))throw new Error("WebAuthn origin nao autorizado");if(value.crossOrigin===true)throw new Error("WebAuthn crossOrigin recusado");return raw}
function verifyRpAndFlags(authData:Buffer,rpId:string,{requireAttested=false,requireUserVerification=true}={}){if(authData.length<37)throw new Error("authenticatorData truncado");const expected=sha256Bytes(rpId);const actual=authData.subarray(0,32);if(!timingSafeEqual(expected,actual))throw new Error("rpIdHash divergente");const flags=authData[32];if((flags&0x01)===0)throw new Error("WebAuthn user presence ausente");if(requireUserVerification&&(flags&0x04)===0)throw new Error("WebAuthn user verification ausente");if(requireAttested&&(flags&0x40)===0)throw new Error("WebAuthn attested credential data ausente");return {flags,signCount:authData.readUInt32BE(33)}}
function parseAttestedCredential(authData:Buffer){const base=verifyRpAndFlags as any;void base;let offset=37;if(authData.length<offset+18)throw new Error("attested credential data truncado");const aaguid=authData.subarray(offset,offset+16);offset+=16;const credentialIdLength=authData.readUInt16BE(offset);offset+=2;if(credentialIdLength<1||offset+credentialIdLength>authData.length)throw new Error("credentialId attested invalido");const credentialId=authData.subarray(offset,offset+credentialIdLength);offset+=credentialIdLength;const decoded=decodeCbor(authData,offset);if(!(decoded.value instanceof Map))throw new Error("COSE public key invalida");return {aaguid:Buffer.from(aaguid),credentialId:Buffer.from(credentialId),cose:decoded.value}}
function coseToPublicKey(cose:Map<any,any>){const kty=cose.get(1);const alg=cose.get(3);if(kty===2&&alg===-7&&cose.get(-1)===1){const x=cose.get(-2);const y=cose.get(-3);if(!Buffer.isBuffer(x)||!Buffer.isBuffer(y)||x.length!==32||y.length!==32)throw new Error("COSE EC2 P-256 invalida");return {algorithm:"ES256",jwk:{kty:"EC",crv:"P-256",x:b64url(x),y:b64url(y),ext:true}}}if(kty===1&&alg===-8&&cose.get(-1)===6){const x=cose.get(-2);if(!Buffer.isBuffer(x)||x.length!==32)throw new Error("COSE Ed25519 invalida");return {algorithm:"EdDSA",jwk:{kty:"OKP",crv:"Ed25519",x:b64url(x),ext:true}}}throw new Error("algoritmo COSE nao suportado; V1 aceita ES256 ou Ed25519")}
function publicKeyFor(record:any){return createPublicKey({key:record.publicKeyJwk,format:"jwk" as any})}
async function atomicWrite(path:string,value:JsonObject){const serialized=`${JSON.stringify(value,null,2)}\n`;if(Buffer.byteLength(serialized)>MAX_RECORD_BYTES)throw new Error(`registro de passkey excede ${MAX_RECORD_BYTES} bytes`);const tmp=`${path}.${process.pid}.${Date.now()}.tmp`;await writeFile(tmp,serialized,{encoding:"utf8",flag:"wx"});await rename(tmp,path)}
function validateRecord(record:any){if(!plain(record)||record.format!==CREATOR_PASSKEY_FORMAT)throw new Error("registro de passkey invalido");if(typeof record.credentialId!=="string"||!B64URL.test(record.credentialId))throw new Error("credentialId de passkey invalido");if(!HASH.test(String(record.credentialIdHash??""))||sha256(record.credentialId)!==record.credentialIdHash)throw new Error("credentialIdHash invalido");if(!["ES256","EdDSA"].includes(record.algorithm))throw new Error("algoritmo de passkey invalido");if(!plain(record.publicKeyJwk))throw new Error("publicKeyJwk invalida");if(!HASH.test(String(record.recordHash??""))||sha256(bodyForHash(record))!==record.recordHash)throw new Error("registro de passkey adulterado");return record}

export type CreatorPasskeyRegistryOptions={rpId:string;allowedOrigins:string[];challengeTtlMs?:number;requireUserVerification?:boolean};

export class CreatorPasskeyRegistry{
  readonly home:string;readonly root:string;readonly credentialsRoot:string;readonly rpId:string;readonly allowedOrigins:Set<string>;readonly challengeTtlMs:number;readonly requireUserVerification:boolean;
  #challenges=new Map<string,{challengeHash:string;purpose:ChallengePurpose;expiresAt:number}>();
  constructor(home:string,options:CreatorPasskeyRegistryOptions){if(!home)throw new Error("home obrigatorio");this.home=resolve(home);this.root=join(this.home,"creator-control","passkeys");this.credentialsRoot=join(this.root,"credentials");this.rpId=normalizeRpId(options?.rpId);if(!Array.isArray(options?.allowedOrigins)||!options.allowedOrigins.length)throw new Error("allowedOrigins obrigatorio");this.allowedOrigins=new Set(options.allowedOrigins.map(normalizeOrigin));this.challengeTtlMs=Number(options.challengeTtlMs??DEFAULT_CHALLENGE_TTL_MS);if(!Number.isSafeInteger(this.challengeTtlMs)||this.challengeTtlMs<10_000||this.challengeTtlMs>5*60*1000)throw new RangeError("challengeTtlMs invalido");this.requireUserVerification=options.requireUserVerification!==false}
  async init(){await mkdir(this.credentialsRoot,{recursive:true})}
  private pathForHash(hash:string){if(!HASH.test(hash))throw new Error("credentialIdHash invalido");return join(this.credentialsRoot,`${hash}.json`)}
  private issue(purpose:ChallengePurpose,{now=new Date()}:{now?:Date}={}){const challenge=randomBytes(32).toString("base64url");const challengeId=`pch-${randomBytes(16).toString("base64url")}`;const expiresAt=now.getTime()+this.challengeTtlMs;this.#challenges.set(challengeId,{challengeHash:sha256(challenge),purpose,expiresAt});return {challengeId,challenge,purpose,expiresAt:new Date(expiresAt).toISOString()}}
  private consume(challengeId:unknown,challenge:unknown,purpose:ChallengePurpose,{now=new Date()}:{now?:Date}={}){if(typeof challengeId!=="string"||!/^pch-[A-Za-z0-9_-]{10,}$/.test(challengeId))throw new Error("challengeId invalido");const record=this.#challenges.get(challengeId);this.#challenges.delete(challengeId);if(!record||record.purpose!==purpose)throw new Error("challenge WebAuthn inexistente ou de finalidade divergente");if(now.getTime()>=record.expiresAt)throw new Error("challenge WebAuthn expirado");if(typeof challenge!=="string"||!constantEqualHex(record.challengeHash,sha256(challenge)))throw new Error("challenge WebAuthn divergente")}
  issueRegistrationOptions(options:{now?:Date;userName?:string;displayName?:string}={}){const grant=this.issue("register",{now:options.now});const userId=sha256Bytes("arca:creator:primary").subarray(0,32);return {...grant,publicKey:{challenge:grant.challenge,rp:{id:this.rpId,name:"ARCA"},user:{id:b64url(userId),name:options.userName??"creator",displayName:options.displayName??"ARCA Creator"},pubKeyCredParams:[{type:"public-key",alg:-7},{type:"public-key",alg:-8}],timeout:this.challengeTtlMs,attestation:"none",authenticatorSelection:{residentKey:"preferred",userVerification:this.requireUserVerification?"required":"preferred"}}}}
  async issueAuthenticationOptions(options:{purpose?:"authenticate"|"step-up";now?:Date}={}){const purpose=options.purpose??"authenticate";const grant=this.issue(purpose,{now:options.now});const active=(await this.list()).filter(item=>!item.revokedAt);return {...grant,publicKey:{challenge:grant.challenge,rpId:this.rpId,allowCredentials:active.map(item=>({type:"public-key",id:item.credentialId})),timeout:this.challengeTtlMs,userVerification:this.requireUserVerification?"required":"preferred"}}}
  async getById(credentialId:string){await this.init();return validateRecord(JSON.parse(await readFile(this.pathForHash(sha256(credentialId)),"utf8")))}
  async list(){await this.init();const out=[];for(const name of (await readdir(this.credentialsRoot)).filter(name=>name.endsWith(".json")).sort()){out.push(validateRecord(JSON.parse(await readFile(join(this.credentialsRoot,name),"utf8")))) }return out.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))}
  async publicList(){return (await this.list()).map(record=>({credentialId:record.credentialId,credentialIdHash:record.credentialIdHash,label:record.label,algorithm:record.algorithm,createdAt:record.createdAt,lastUsedAt:record.lastUsedAt,revokedAt:record.revokedAt}))}
  async register(input:any,{now=new Date()}:{now?:Date}={}){
    await this.init();if(!plain(input)||!plain(input.credential)||input.credential.type!=="public-key"||!plain(input.credential.response))throw new Error("credential WebAuthn de registro invalida");const id=String(input.credential.id??"");const client=parseClientData(input.credential.response.clientDataJSON);this.consume(input.challengeId,client.value.challenge,"register",{now});const clientRaw=verifyClientData({encoded:input.credential.response.clientDataJSON,expectedType:"webauthn.create",expectedChallenge:client.value.challenge,allowedOrigins:this.allowedOrigins});void clientRaw;
    const attestation=decodeCbor(bytes(input.credential.response.attestationObject,"attestationObject"));if(attestation.offset!==bytes(input.credential.response.attestationObject,"attestationObject").length)throw new Error("attestationObject contem bytes extras");const map=attestation.value;if(!(map instanceof Map))throw new Error("attestationObject deve ser CBOR map");const fmt=mapValue(map,"fmt");const attStmt=mapValue(map,"attStmt");if(fmt!=="none"||!(attStmt instanceof Map)||attStmt.size!==0)throw new Error("V1 aceita somente attestation fmt=none");const authData=mapValue(map,"authData");if(!Buffer.isBuffer(authData))throw new Error("authData ausente no attestationObject");const auth=verifyRpAndFlags(authData,this.rpId,{requireAttested:true,requireUserVerification:this.requireUserVerification});const attested=parseAttestedCredential(authData);const attestedId=b64url(attested.credentialId);if(id!==attestedId)throw new Error("credentialId divergente do authenticatorData");if(!B64URL.test(id))throw new Error("credentialId invalido");const key=coseToPublicKey(attested.cose);const credentialIdHash=sha256(id);if(await this.existsByHash(credentialIdHash))throw new Error("passkey ja registrada");const createdAt=now.toISOString();const record=seal({format:CREATOR_PASSKEY_FORMAT,version:CREATOR_PASSKEY_VERSION,credentialId:id,credentialIdHash,label:safeLabel(input.label),algorithm:key.algorithm,publicKeyJwk:key.jwk,publicKeyHash:sha256(key.jwk),aaguidHash:sha256(b64url(attested.aaguid)),signCount:auth.signCount,createdAt,updatedAt:createdAt,lastUsedAt:null,revokedAt:null,revocationReason:null});const handle=await open(this.pathForHash(credentialIdHash),"wx");try{const serialized=`${JSON.stringify(record,null,2)}\n`;await handle.writeFile(serialized,"utf8")}finally{await handle.close()}return record;
  }
  private async existsByHash(hash:string){try{await readFile(this.pathForHash(hash));return true}catch(error:any){if(error?.code==="ENOENT")return false;throw error}}
  async verifyAssertion(input:any,{purpose="authenticate",now=new Date()}:{purpose?:"authenticate"|"step-up";now?:Date}={}){
    if(!plain(input)||!plain(input.credential)||input.credential.type!=="public-key"||!plain(input.credential.response))throw new Error("credential WebAuthn assertion invalida");const id=String(input.credential.id??"");const current=await this.getById(id);if(current.revokedAt)throw new Error("passkey revogada");const client=parseClientData(input.credential.response.clientDataJSON);this.consume(input.challengeId,client.value.challenge,purpose,{now});const clientRaw=verifyClientData({encoded:input.credential.response.clientDataJSON,expectedType:"webauthn.get",expectedChallenge:client.value.challenge,allowedOrigins:this.allowedOrigins});const authData=bytes(input.credential.response.authenticatorData,"authenticatorData");const auth=verifyRpAndFlags(authData,this.rpId,{requireUserVerification:this.requireUserVerification});const signature=bytes(input.credential.response.signature,"signature");const signed=Buffer.concat([authData,sha256Bytes(clientRaw)]);const key=publicKeyFor(current);const valid=current.algorithm==="ES256"?verifySignature("sha256",signed,key,signature):verifySignature(null,signed,key,signature);if(!valid)throw new Error("assinatura WebAuthn invalida");if(current.signCount>0&&auth.signCount>0&&auth.signCount<=current.signCount)throw new Error("contador WebAuthn nao monotono; possivel replay/clonagem");const latest=await this.getById(id);if(latest.recordHash!==current.recordHash)throw new Error("Conflito de concorrencia no registro de passkey");const updated=seal({...bodyForHash(current),signCount:Math.max(Number(current.signCount??0),auth.signCount),lastUsedAt:now.toISOString(),updatedAt:now.toISOString()});await atomicWrite(this.pathForHash(current.credentialIdHash),updated);return {format:CREATOR_PASSKEY_ASSERTION_FORMAT,purpose,credentialIdHash:current.credentialIdHash,subject:"creator:primary",userVerified:(auth.flags&0x04)!==0,verifiedAt:now.toISOString(),recordHash:updated.recordHash};
  }
  async revoke(input:{credentialId:string;reason:string;expectedRecordHash:string},{now=new Date()}:{now?:Date}={}){const current=await this.getById(input.credentialId);if(current.revokedAt)return current;if(!HASH.test(String(input.expectedRecordHash??""))||current.recordHash!==input.expectedRecordHash)throw new Error("Conflito de concorrencia no registro de passkey");const reason=String(input.reason??"").trim();if(!reason||reason.length>1000)throw new Error("reason de revogacao invalido");const next=seal({...bodyForHash(current),revokedAt:now.toISOString(),revocationReason:reason,updatedAt:now.toISOString()});await atomicWrite(this.pathForHash(current.credentialIdHash),next);return next}
}
